### ISSUE TITLE
Ошибка ExportedObject3D.GetDynamoGeometry

### ISSUE THREAD

**Issue by bkamuz** [GeorgGrebenyuk/RengaDyn#1]
Привет! А этот проект еще жив? (надеюсь 🙏)

Не выходит подгрузить геометрию из Renga в Dynamo
Версия Dynamo 2.12.0 (также пробовал 2.18.1)
Версия Renga 6.0

<img width="1127" alt="image" src="https://github.com/GeorgGrebenyuk/RengaDyn/assets/118307284/10b68e6e-1a3b-472c-9b31-caf64070ab89">

Также пробовал иные пути добычи геометрии и обнаружил еще вот такую ошибку, возможно поможет

<img width="539" alt="image" src="https://github.com/GeorgGrebenyuk/RengaDyn/assets/118307284/3a2c1e0d-6f4a-4ec3-91ce-888bd9f5d7d7">

В целом куда копать что бы решить это? Застопорился и дальше ничего не могу сделать.

**Comment by bkamuz** [comment]
Похоже ошибка в версии 1.5.1 ибо 1.5.0 работает как часы, любая геометрия выгружается без проблем. Попробую понять какие были различия что могло привести к таким проблемам. Отпишусь как только будут результаты.

**Comment by GeorgGrebenyuk** [comment]
Извиняюсь за отсутствие связи, уведомления не работали.
В Динамо всё сложно оттого, что скачиваемая версия Sandbox по умолчанию неполная, она ищет а в реестре установленные продукты Autodesk и библиотеки при них -- и они могут не полностью соответствовать функциям (не знаю, как проще объяснить)

А вообще, я бросил разработку под Dynamo для продуктов с COM API (ActiveX), потому что они порождают кучу ошибок (как у вас на скрине), которых нет в трекере Dynamo Sandbox и невозможно понять почему на каком-то этапе библиотеки вообще не грузятся в dynamo или работают не так. Да и не развивается Renga API нифига .... 😥

**Comment by GeorgGrebenyuk** [comment]
Здравствуйте!
Возвращаясь к ошибке, я тут на днях сильно обновил пакет - попробуйте снова эту операцию на текущей версии 1.6.0+
![image](https://github.com/GeorgGrebenyuk/RengaDyn/assets/55656376/08f5f281-634b-420b-8f24-20b163f05e73)
Геометрия должна получаться без ошибок

**Comment by bkamuz** [comment]
Добрый день! Большое спасибо. Сегодня проверю
